# Generated by Django 5.2.16 on 2026-07-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
