# Generated by Django 5.2.16 on 2026-09-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='section',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
