# Generated by Django 6.0.2 on 2026-04-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Publish', 'Publish'), ('Trending', 'Trending'), ('Main_Post', 'Main_Post')], default='Recent', max_length=20),
        ),
    ]
