# Generated by Django 6.0.2 on 2026-04-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_blog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Popular', 'Popular'), ('Trending', 'Trending'), ('Main_Post', 'Main_Post')], default='Recent', max_length=20),
        ),
    ]
