# Generated by Django 6.0.2 on 2026-04-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_blog_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
