# Generated by Django 6.0.2 on 2026-04-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0010_remove_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_name',
            new_name='author',
        ),
    ]
