# Generated by Django 6.0.2 on 2026-04-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0011_rename_author_name_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='author_name',
        ),
    ]
