# Generated by Django 6.0.2 on 2026-04-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0012_rename_author_blog_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_name',
            new_name='author',
        ),
    ]
