# Generated by Django 6.0.2 on 2026-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0013_rename_author_name_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], default='PUBLISH', max_length=1),
        ),
    ]
