# Generated by Django 6.0.2 on 2026-04-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0015_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
